"""Public claims must match the repository they describe.

Skill, demo and CLI counts are never hand-typed into the public files below:
the only source is skills/catalog.json (the README shows it through a live
badge). Hand-typed counts made every new-skill PR conflict with every other
(2026-10-08: four green PRs had to merge one at a time). The release version is
still repeated by hand and checked against its source of truth. The plan that produced this gate found the
README, CITATION.cff, .zenodo.json and llms.txt disagreeing with each other by
up to 55 skills and two minor releases, and a "first" claim that no evidence
supports. A stale public claim is a defect, so this test fails CI on drift.

Sources of truth:
  skill counts   skills/catalog.json (written by scripts/generate_catalog.py)
  version        clawbio/__init__.py

How to fix a count failure: delete the number and point at `skill_count` in
skills/catalog.json (regenerated by `python scripts/generate_catalog.py`). To bump the version, change clawbio/__init__.py first.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "skills" / "catalog.json"

# Public files that must NOT carry a literal skill, demo or CLI count.
COUNT_FILES = [
    "README.md",
    "llms.txt",
    "CITATION.cff",
    ".zenodo.json",
    ".claude-plugin/plugin.json",
    ".claude-plugin/marketplace.json",
]

# Files that state the current release. Each must carry the package version.
VERSION_FILES = {
    "README.md": r"The current release is \*\*v([0-9][0-9a-z.\-]*)\*\*",
    "llms.txt": r"Current public release: `v([0-9][0-9a-z.\-]*)`",
    "CITATION.cff": r"^version: ([0-9][0-9a-z.\-]*)$",
    ".zenodo.json": r'"version": "([0-9][0-9a-z.\-]*)"',
    ".claude-plugin/plugin.json": r'"version": "([0-9][0-9a-z.\-]*)"',
    ".claude-plugin/marketplace.json": r'"version": "([0-9][0-9a-z.\-]*)"',
}

# A primacy claim the project cannot evidence. Scanned across every tracked
# text file; the allowlist holds dated records of past talks and submissions,
# which are history and are not rewritten.
PRIMACY = re.compile(
    r"\bfirst\s+bioinformatics[\s-]native\b|\bfirst\s+(?:AI\s+)?agent\s+skill\s+library\b",
    re.IGNORECASE,
)
PRIMACY_ALLOWLIST_PREFIXES = (
    "slides/",  # London Bioinformatics Meetup deck, February 2026, as delivered
    "docs/dorahacks-buidl-submission.md",  # submission text as filed, 5 March 2026
    "tests/test_public_claims.py",
)
TEXT_SUFFIXES = {".md", ".txt", ".toml", ".json", ".cff", ".html", ".py", ".yml", ".yaml", ".cfg", ".ini"}

COUNT_PATTERN = re.compile(r"(?<![\d.,])(\d[\d,]*)\s+(?:Agent\s+)?skills\b", re.IGNORECASE)
DEMO_PATTERN = re.compile(r"(\d+) with runnable demo data")
CLI_PATTERN = re.compile(r"(\d+) (?:with a deterministic CLI entry point|run deterministically from the CLI)")


def _catalog() -> dict:
    return json.loads(CATALOG.read_text())


def _package_version() -> str:
    text = (ROOT / "clawbio" / "__init__.py").read_text()
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', text, re.MULTILINE)
    assert match, "clawbio/__init__.py has no __version__"
    return match.group(1)


def _tracked_text_files() -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=ROOT, capture_output=True, check=True
    ).stdout
    paths = [ROOT / p for p in out.decode().split("\0") if p]
    return [p for p in paths if p.suffix in TEXT_SUFFIXES and p.is_file()]


def test_catalog_skill_count_matches_skill_entries():
    cat = _catalog()
    assert cat["skill_count"] == len(cat["skills"]), "catalog.json is internally inconsistent; regenerate it"


def _hand_typed_counts(text: str) -> list[str]:
    """Every skill, demo or CLI count written as a literal number in text."""
    hits = [m.group(0) for m in COUNT_PATTERN.finditer(text)]
    hits += [m.group(0) for m in DEMO_PATTERN.finditer(text)]
    hits += [m.group(0) for m in CLI_PATTERN.finditer(text)]
    return hits


@pytest.mark.parametrize("relpath", COUNT_FILES)
def test_no_hand_typed_counts(relpath: str):
    text = (ROOT / relpath).read_text()
    found = _hand_typed_counts(text)
    assert not found, (
        f"{relpath} hand-types a count {found}. Counts live only in skills/catalog.json "
        "(skill_count); refer to it or use the README badge instead, so new-skill PRs "
        "do not conflict with each other."
    )


@pytest.mark.parametrize(
    "text",
    [
        "ClawBio ships 105 skills for genomics.",
        "104 Agent Skills, local-first.",
        "1,104 skills",
        "98 with runnable demo data",
        "56 with a deterministic CLI entry point",
        "56 run deterministically from the CLI",
    ],
)
def test_hand_typed_count_guard_still_fires(text: str):
    assert _hand_typed_counts(text), f"guard is disarmed: did not flag {text!r}"


def test_count_free_wording_is_not_flagged():
    text = "Every skill is listed in skills/catalog.json; see `skill_count`. Agent Skills for genomics."
    assert _hand_typed_counts(text) == []


@pytest.mark.parametrize("relpath,pattern", sorted(VERSION_FILES.items()))
def test_stated_release_matches_package_version(relpath: str, pattern: str):
    expected = _package_version()
    text = (ROOT / relpath).read_text()
    found = re.findall(pattern, text, re.MULTILINE)
    assert found, f"{relpath} states no release version (pattern {pattern!r})"
    wrong = sorted(set(v for v in found if v != expected))
    assert not wrong, f"{relpath} states release {wrong}, package is {expected}"


def test_no_primacy_claim_anywhere():
    hits = []
    for path in _tracked_text_files():
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith(PRIMACY_ALLOWLIST_PREFIXES):
            continue
        for lineno, line in enumerate(path.read_text(errors="ignore").splitlines(), 1):
            if PRIMACY.search(line):
                hits.append(f"{rel}:{lineno}: {line.strip()[:100]}")
    assert not hits, "primacy claim found (the project does not evidence it):\n" + "\n".join(hits)
