"""Embedding-quality metrics for scrna-embedding-audit.

Every scIB metric here follows the definition in scib-metrics 0.6.1 (that
package cannot be a ClawBio dependency: it needs Python >= 3.12 and JAX),
re-implemented with numpy, scipy and scikit-learn and held to a fixture
generated by that release (``fixtures/generate_scib_fixture.py``). One metric
is the skill's own and is marked as such: ``knn_transfer_accuracy``.

All metrics are oriented so that higher is better. Every metric lies in
``[0, 1]`` except ``ari_kmeans`` (adjusted Rand index, which can be negative).
Functions raise ``ValueError`` on input they cannot score; ``score_embedding``
turns those into ``None`` plus a named reason so that the caller never reports
a number that was not computed.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components
from sklearn.cluster import KMeans
from sklearn.metrics import (
    adjusted_rand_score,
    normalized_mutual_info_score,
    pairwise_distances,
    silhouette_samples,
)
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors

# Loaded by scrna_embedding_audit.py through importlib (no package), so the public
# surface is declared here; the constants are read by the main script and the tests.
__all__ = [
    "BATCH_METRICS",
    "BIO_METRICS",
    "CEILING",
    "DIFF_TOLERANCE",
    "GROUP_TITLES",
    "METRIC_DEFINITIONS",
    "METRIC_GROUPS",
    "METRIC_NAMES",
    "OMITTED_METRICS",
    "SD_FACTOR",
    "TRANSFER_METRICS",
    "bras",
    "clisi",
    "degeneracy_reason",
    "duplicate_row_fraction",
    "exact_knn",
    "graph_connectivity",
    "ilisi",
    "isolated_labels",
    "kmeans_nmi_ari",
    "knn_transfer_accuracy",
    "lisi_per_cell",
    "score_embedding",
    "silhouette_batch",
    "silhouette_label",
    "stratified_subsample",
    "verdict",
]

BIO_METRICS = (
    "silhouette_label",
    "isolated_labels",
    "nmi_kmeans",
    "ari_kmeans",
    "clisi",
)
BATCH_METRICS = (
    "bras",
    "silhouette_batch",
    "ilisi",
    "graph_connectivity",
)
TRANSFER_METRICS = ("knn_transfer_accuracy",)
METRIC_NAMES = BIO_METRICS + BATCH_METRICS + TRANSFER_METRICS
METRIC_GROUPS = {
    **{name: "bio" for name in BIO_METRICS},
    **{name: "batch" for name in BATCH_METRICS},
    **{name: "transfer" for name in TRANSFER_METRICS},
}
GROUP_TITLES = {
    "bio": "biological conservation",
    "batch": "batch mixing",
    "transfer": "cross-batch label transfer",
}

# One-line definitions printed into result.json so a reader of the output does
# not have to open this file. The source string names where the definition comes from.
METRIC_DEFINITIONS: dict[str, dict[str, str]] = {
    "silhouette_label": {
        "definition": "mean euclidean silhouette of cells by label, rescaled (s + 1) / 2",
        "source": "scib-metrics 0.6.1 silhouette_label; Luecken et al. 2022",
    },
    "isolated_labels": {
        "definition": "mean over isolated labels (labels present in the fewest batches) of their mean rescaled silhouette",
        "source": "scib-metrics 0.6.1 isolated_labels (ASW variant); Luecken et al. 2022",
    },
    "nmi_kmeans": {
        "definition": "normalised mutual information (arithmetic mean) between labels and KMeans clusters with k = number of labels",
        "source": "scib-metrics 0.6.1 nmi_ari_cluster_labels_kmeans; sklearn KMeans(n_init=10) here, jax KMeans(n_init=1) upstream, so values are not numerically comparable to a Benchmarker run",
    },
    "ari_kmeans": {
        "definition": "adjusted Rand index between labels and the same KMeans clusters as nmi_kmeans; can be negative",
        "source": "scib-metrics 0.6.1 nmi_ari_cluster_labels_kmeans; shares one clustering with nmi_kmeans",
    },
    "clisi": {
        "definition": "median per-cell LISI over labels on the k-NN graph, scaled (n_labels - median) / (n_labels - 1)",
        "source": "scib-metrics 0.6.1 clisi_knn; Korsunsky et al. 2019",
    },
    "bras": {
        "definition": "batch-removal-adapted silhouette: per label, 1 - |cosine silhouette by batch with mean distance to all other batches|; mean per label, mean over labels",
        "source": "scib-metrics 0.6.1 bras (the Benchmarker default batch ASW since that release)",
    },
    "silhouette_batch": {
        "definition": "legacy scIB batch ASW: per label with >= 2 batches, mean of 1 - |euclidean silhouette by batch|; mean over labels",
        "source": "scib-metrics 0.6.1 silhouette_batch; Luecken et al. 2022; retired from the Benchmarker defaults in favour of bras",
    },
    "ilisi": {
        "definition": "median per-cell LISI over batches on the k-NN graph, scaled (median - 1) / (n_batches - 1)",
        "source": "scib-metrics 0.6.1 ilisi_knn; Korsunsky et al. 2019",
    },
    "graph_connectivity": {
        "definition": "per label, size of the largest strongly connected component of the induced directed k-NN subgraph over label size; mean over labels",
        "source": "scib-metrics 0.6.1 graph_connectivity; Luecken et al. 2022",
    },
    "knn_transfer_accuracy": {
        "definition": "leave-one-batch-out distance-weighted kNN label transfer; balanced accuracy over labels present in the training batches, pooled over held-out batches; cells whose label is absent from training are counted separately",
        "source": "this skill's own metric (not part of scIB)",
    },
}

OMITTED_METRICS: dict[str, str] = {
    "kbet_per_label": "omitted: kBET needs a per-label chi-square acceptance rate with its own neighbourhood size and rejection threshold; not reproduced in v0.1",
    "pcr_comparison": "omitted: principal-component regression against the pre-integration matrix scores the PCA baseline as 0 by construction, so it cannot compare embedding and baseline",
    "nmi_ari_cluster_labels_leiden": "omitted: Leiden clustering with resolution search is not deterministic across igraph versions; the Benchmarker default is the KMeans variant",
}

REASON_NO_BATCH = "not computed: no batch key given"
REASON_FEW_BATCHES = "not computed: fewer than 2 batches"
REASON_FEW_LABELS = "not computed: fewer than 2 labels"
REASON_SIL_BATCH_UNDEFINED = "undefined: no label contains more than one batch"
CEILING = 0.999  # both values at or above this: "tied" (skill's choice)
DIFF_TOLERANCE = 1e-5  # |difference| at or below this counts as zero (skill's choice)
SD_FACTOR = 2.0  # median difference must exceed this many SDs (skill's choice)


def _codes(values: Any) -> tuple[np.ndarray, int]:
    arr = np.asarray(values)
    if arr.ndim != 1:
        raise ValueError("labels must be one-dimensional")
    uniq, codes = np.unique(arr.astype(str), return_inverse=True)
    return codes.astype(np.int64), len(uniq)


def _check_matrix(x: Any, name: str = "embedding") -> np.ndarray:
    arr = np.asarray(x, dtype=np.float64)
    if arr.ndim != 2:
        raise ValueError(f"{name} must be a 2-D array, got shape {arr.shape}")
    if arr.shape[0] == 0:
        raise ValueError(f"{name} has no cells")
    return arr


def _check_lengths(arr: np.ndarray, *vectors: np.ndarray) -> None:
    for vec in vectors:
        if vec.shape[0] != arr.shape[0]:
            raise ValueError(
                "labels, batches and embedding disagree on the number of cells"
            )


def degeneracy_reason(x: Any) -> str | None:
    """Return why an embedding cannot be scored, or None when it can.

    The variance check runs on the raw values (``np.ptp``), not on centred
    floats, so ``np.full(n, 0.1)`` is recognised as constant.
    """
    arr = np.asarray(x, dtype=np.float64)
    if not np.all(np.isfinite(arr)):
        n_bad = int(np.sum(~np.all(np.isfinite(arr), axis=1))) if arr.ndim == 2 else 0
        return f"non-finite values in {n_bad} cells" if n_bad else "non-finite values"
    if arr.size == 0:
        return "empty embedding"
    if arr.ndim == 2 and np.all(np.ptp(arr, axis=0) == 0.0):
        return "zero variance in every dimension"
    return None


def duplicate_row_fraction(x: Any) -> float:
    """Fraction of cells whose coordinates coincide exactly with another cell's."""
    arr = _check_matrix(x)
    _, inverse, counts = np.unique(arr, axis=0, return_inverse=True, return_counts=True)
    return float(np.mean(counts[inverse] > 1))


# --- neighbours --------------------------------------------------------------


def exact_knn(x: Any, k: int) -> tuple[np.ndarray, np.ndarray]:
    """Exact euclidean k nearest neighbours, self in column 0 at distance 0.

    Matches the ``NeighborsResults`` layout scib-metrics expects: ``k`` columns
    including self, neighbours sorted by distance. Self is placed explicitly
    (``kneighbors(X=None)`` excludes each query's own index even when other
    cells share its coordinates), so duplicate cells cannot drop the self edge.
    Ties among the remaining neighbours are broken by scikit-learn's stable
    ordering, so metrics on exactly duplicated cells can depend on cell order.
    ``k`` must satisfy ``1 <= k <= n_cells``.
    """
    arr = _check_matrix(x)
    n = arr.shape[0]
    if not 1 <= k <= n:
        raise ValueError(f"k must be between 1 and n_cells={n}, got {k}")
    self_idx = np.arange(n)[:, None]
    self_dist = np.zeros((n, 1))
    if k == 1:
        return self_dist, self_idx
    nn = NearestNeighbors(n_neighbors=k - 1, metric="euclidean", algorithm="brute").fit(
        arr
    )
    dists, idx = nn.kneighbors(X=None)
    return np.hstack([self_dist, dists]), np.hstack([self_idx, idx])


# --- silhouette family -------------------------------------------------------


def silhouette_label(x: Any, labels: Any) -> float:
    """scib-metrics ``silhouette_label``: mean silhouette by label, rescaled to [0, 1]."""
    arr = _check_matrix(x)
    codes, n_labels = _codes(labels)
    _check_lengths(arr, codes)
    if n_labels < 2:
        raise ValueError(REASON_FEW_LABELS)
    if n_labels >= arr.shape[0]:
        raise ValueError("silhouette needs fewer labels than cells")
    asw = float(np.mean(silhouette_samples(arr, codes, metric="euclidean")))
    return (asw + 1.0) / 2.0


def isolated_labels(x: Any, labels: Any, batches: Any) -> float:
    """scib-metrics ``isolated_labels`` (ASW variant).

    Isolated labels are those present in the smallest number of batches. The
    score is the mean over isolated labels of the mean rescaled euclidean
    silhouette (computed against all labels) of their cells.
    """
    arr = _check_matrix(x)
    codes, n_labels = _codes(labels)
    batches = np.asarray(batches).astype(str)
    _check_lengths(arr, codes, batches)
    if n_labels < 2:
        raise ValueError(REASON_FEW_LABELS)
    if n_labels >= arr.shape[0]:
        raise ValueError("silhouette needs fewer labels than cells")
    batches_per_label = np.array(
        [len(np.unique(batches[codes == c])) for c in range(n_labels)]
    )
    iso_threshold = int(batches_per_label.min())
    isolated = np.flatnonzero(batches_per_label <= iso_threshold)
    sil = (silhouette_samples(arr, codes, metric="euclidean") + 1.0) / 2.0
    return float(np.mean([np.mean(sil[codes == c]) for c in isolated]))


def _batch_silhouette_groups(
    arr: np.ndarray, labels: np.ndarray, batches: np.ndarray, per_group
) -> float | None:
    group_means: list[float] = []
    for group in np.unique(labels):
        mask = labels == group
        b_sub = batches[mask]
        n_batches = len(np.unique(b_sub))
        if n_batches == 1 or n_batches == int(mask.sum()):
            continue
        s = np.abs(per_group(arr[mask], b_sub))
        group_means.append(float(np.mean(1.0 - s)))
    if not group_means:
        return None
    return float(np.mean(group_means))


def silhouette_batch(x: Any, labels: Any, batches: Any) -> float | None:
    """scib-metrics ``silhouette_batch`` (legacy scIB batch ASW); ``None`` when undefined."""
    arr = _check_matrix(x)
    labels = np.asarray(labels).astype(str)
    batches = np.asarray(batches).astype(str)
    _check_lengths(arr, labels, batches)
    return _batch_silhouette_groups(
        arr,
        labels,
        batches,
        lambda sub, b: silhouette_samples(sub, b, metric="euclidean"),
    )


def _silhouette_mean_other(
    sub: np.ndarray, groups: np.ndarray, metric: str
) -> np.ndarray:
    """Silhouette with the between-cluster term = mean distance to all other clusters.

    Mirrors ``scib_metrics.utils.silhouette_samples(between_cluster_distances="mean_other")``.
    """
    codes, n_groups = _codes(groups)
    dist = pairwise_distances(sub, metric=metric)
    if metric == "cosine":
        dist = np.clip(dist, 0.0, 2.0)
    freqs = np.bincount(codes, minlength=n_groups).astype(np.float64)
    clust = np.zeros((sub.shape[0], n_groups))
    for c in range(n_groups):
        clust[:, c] = dist[:, codes == c].sum(axis=1)
    own = clust[np.arange(sub.shape[0]), codes]
    with np.errstate(divide="ignore", invalid="ignore"):
        intra = own / (freqs[codes] - 1.0)
        other_total = clust.sum(axis=1) - own
        inter = other_total / (freqs.sum() - freqs[codes])
        s = (inter - intra) / np.maximum(intra, inter)
    return np.nan_to_num(s)


def bras(x: Any, labels: Any, batches: Any) -> float | None:
    """scib-metrics ``bras``: batch-removal-adapted silhouette (cosine, mean_other)."""
    arr = _check_matrix(x)
    labels = np.asarray(labels).astype(str)
    batches = np.asarray(batches).astype(str)
    _check_lengths(arr, labels, batches)
    if np.any(np.linalg.norm(arr, axis=1) == 0.0):
        raise ValueError("cosine distance is undefined for all-zero cells")
    return _batch_silhouette_groups(
        arr, labels, batches, lambda sub, b: _silhouette_mean_other(sub, b, "cosine")
    )


# --- clustering agreement ----------------------------------------------------


def kmeans_nmi_ari(
    x: Any, labels: Any, random_state: int = 0
) -> tuple[float, float, np.ndarray]:
    """scib-metrics ``nmi_ari_cluster_labels_kmeans`` with scikit-learn's KMeans.

    Returns (nmi, ari, predicted_cluster_labels).
    """
    arr = _check_matrix(x)
    codes, n_labels = _codes(labels)
    _check_lengths(arr, codes)
    if n_labels < 2:
        raise ValueError(REASON_FEW_LABELS)
    km = KMeans(n_clusters=n_labels, n_init=10, random_state=random_state).fit(arr)
    pred = km.labels_
    nmi = float(normalized_mutual_info_score(codes, pred, average_method="arithmetic"))
    ari = float(adjusted_rand_score(codes, pred))
    return nmi, ari, pred


# --- LISI --------------------------------------------------------------------


def _simpson_index(
    knn_dists: np.ndarray,
    knn_idx: np.ndarray,
    codes: np.ndarray,
    n_cats: int,
    perplexity: float,
    tol: float = 1e-5,
    max_tries: int = 50,
) -> np.ndarray:
    """Per-cell Simpson index with a perplexity-calibrated Gaussian kernel.

    Mirrors ``scib_metrics.utils.compute_simpson_index`` (Harmony's LISI):
    binary search on the kernel bandwidth ``beta`` until the entropy equals
    ``log(perplexity)``, self edge masked out, at most 50 iterations.
    """
    d = np.asarray(knn_dists, dtype=np.float64)
    n = d.shape[0]
    self_mask = np.asarray(knn_idx) != np.arange(n)[:, None]
    knn_codes = np.asarray(codes)[np.asarray(knn_idx)]
    log_perp = np.log(perplexity)

    def hbeta(beta: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        p = np.exp(-d * beta[:, None])
        p = np.where(self_mask, p, 0.0)
        sum_p = np.sum(p, axis=1)
        safe = np.where(sum_p == 0, 1.0, sum_p)
        h = np.where(
            sum_p == 0, 0.0, np.log(safe) + beta * np.sum(d * p, axis=1) / safe
        )
        p = np.where((sum_p == 0)[:, None], 0.0, p / safe[:, None])
        return h, p

    beta = np.ones(n)
    betamin = np.full(n, -np.inf)
    betamax = np.full(n, np.inf)
    h, p = hbeta(beta)
    hdiff = h - log_perp
    tries = 0
    active = np.abs(hdiff) >= tol
    while active.any() and tries < max_tries:
        up = hdiff > 0
        new_betamin = np.where(up, beta, betamin)
        new_betamax = np.where(up, betamax, beta)
        new_beta = np.where(
            up,
            np.where(np.isinf(betamax), beta * 2.0, (beta + betamax) / 2.0),
            np.where(np.isinf(betamin), beta / 2.0, (beta + betamin) / 2.0),
        )
        beta = np.where(active, new_beta, beta)
        betamin = np.where(active, new_betamin, betamin)
        betamax = np.where(active, new_betamax, betamax)
        h_new, p_new = hbeta(beta)
        h = np.where(active, h_new, h)
        p = np.where(active[:, None], p_new, p)
        hdiff = h - log_perp
        tries += 1
        active = np.abs(hdiff) >= tol

    sums = np.zeros((n, n_cats))
    for c in range(n_cats):
        sums[:, c] = np.sum(np.where(knn_codes == c, p, 0.0), axis=1)
    simpson = np.sum(sums * sums, axis=1)
    return np.where(h == 0, -1.0, simpson)


def lisi_per_cell(
    knn_dists: Any, knn_idx: Any, values: Any, perplexity: float | None = None
) -> np.ndarray:
    """Per-cell local inverse Simpson index over ``values`` (scib-metrics ``lisi_knn``).

    Regular values lie in ``[1, n_categories]``. A cell whose neighbours are all
    equidistant (for example exact duplicates) has no bandwidth that reaches the
    target perplexity; scib-metrics assigns such a cell ``-1`` and so does this
    function, so that the two agree on the fixture. ``score_embedding`` counts
    these cells and the report warns when the count is non-zero.
    """
    knn_idx = np.asarray(knn_idx)
    codes, n_cats = _codes(values)
    if codes.shape[0] != knn_idx.shape[0]:
        raise ValueError("values and kNN graph disagree on the number of cells")
    if perplexity is None:
        perplexity = float(np.floor(knn_idx.shape[1] / 3))
    if perplexity <= 1:
        raise ValueError("perplexity must exceed 1; use more neighbours")
    return 1.0 / _simpson_index(knn_dists, knn_idx, codes, n_cats, perplexity)


def ilisi(
    knn_dists: Any, knn_idx: Any, batches: Any, perplexity: float | None = None
) -> float:
    """scib-metrics ``ilisi_knn``: scaled median batch LISI, 1 = perfect mixing."""
    codes, n_batches = _codes(batches)
    if n_batches < 2:
        raise ValueError(REASON_FEW_BATCHES)
    med = float(np.nanmedian(lisi_per_cell(knn_dists, knn_idx, codes, perplexity)))
    return float(np.clip((med - 1.0) / (n_batches - 1.0), 0.0, 1.0))


def clisi(
    knn_dists: Any, knn_idx: Any, labels: Any, perplexity: float | None = None
) -> float:
    """scib-metrics ``clisi_knn``: scaled median label LISI, 1 = pure neighbourhoods."""
    codes, n_labels = _codes(labels)
    if n_labels < 2:
        raise ValueError(REASON_FEW_LABELS)
    med = float(np.nanmedian(lisi_per_cell(knn_dists, knn_idx, codes, perplexity)))
    return float(np.clip((n_labels - med) / (n_labels - 1.0), 0.0, 1.0))


# --- graph connectivity ------------------------------------------------------


def graph_connectivity(knn_dists: Any, knn_idx: Any, labels: Any) -> float:
    """scib-metrics ``graph_connectivity`` on the directed k-NN distance graph.

    Strongly connected components are used, as upstream: a cell that no other
    cell lists as a neighbour is its own component, so even one Gaussian blob
    scores below 1 when it has such boundary cells.
    """
    knn_idx = np.asarray(knn_idx)
    knn_dists = np.asarray(knn_dists, dtype=np.float64)
    labels = np.asarray(labels).astype(str)
    n, k = knn_idx.shape
    if labels.shape[0] != n:
        raise ValueError("labels and kNN graph disagree on the number of cells")
    indptr = np.arange(0, n * k + 1, k)
    graph = csr_matrix((knn_dists.ravel(), knn_idx.ravel(), indptr), shape=(n, n))
    fractions: list[float] = []
    for label in np.unique(labels):
        mask = labels == label
        sub = graph[mask][:, mask]
        _, comps = connected_components(sub, directed=True, connection="strong")
        counts = np.bincount(comps)
        fractions.append(float(counts.max() / counts.sum()))
    return float(np.mean(fractions))


# --- label transfer (skill's own metric) -------------------------------------


def knn_transfer_accuracy(x: Any, labels: Any, batches: Any, k: int) -> dict[str, Any]:
    """Leave-one-batch-out kNN label transfer. This skill's own metric.

    For each batch, a distance-weighted ``KNeighborsClassifier`` (euclidean) is
    fitted on every other batch and predicts the held-out batch. The score is
    the balanced accuracy (mean per-label recall) over held-out cells whose
    label occurs in the training batches, pooled across batches. Cells whose
    label never appears in the training batches cannot be recovered; they are
    counted in ``n_cells_with_unseen_label`` and excluded from the balanced
    accuracy rather than silently lowering it.
    """
    arr = _check_matrix(x)
    labels = np.asarray(labels).astype(str)
    batches = np.asarray(batches).astype(str)
    _check_lengths(arr, labels, batches)
    uniq_batches = np.unique(batches)
    if len(uniq_batches) < 2:
        raise ValueError(REASON_FEW_BATCHES)
    if k < 1:
        raise ValueError("k must be at least 1")
    pred_all = np.empty(arr.shape[0], dtype=object)
    seen = np.zeros(arr.shape[0], dtype=bool)
    per_batch: dict[str, float] = {}
    for batch in uniq_batches:
        test = batches == batch
        train = ~test
        train_labels = labels[train]
        k_eff = min(k, int(train.sum()))
        clf = KNeighborsClassifier(
            n_neighbors=k_eff, weights="distance", metric="euclidean"
        )
        clf.fit(arr[train], train_labels)
        pred = clf.predict(arr[test])
        pred_all[test] = pred
        seen[test] = np.isin(labels[test], np.unique(train_labels))
        hits = pred == labels[test]
        per_batch[str(batch)] = float(np.mean(hits)) if hits.size else float("nan")
    unseen = int(np.sum(~seen))
    if not seen.any():
        raise ValueError("no held-out cell has a label present in the other batches")
    recalls = [
        float(np.mean(pred_all[seen & (labels == lab)] == lab))
        for lab in np.unique(labels[seen])
    ]
    return {
        "accuracy": float(np.mean(recalls)),
        "per_batch_accuracy": per_batch,
        "n_cells_with_unseen_label": unseen,
        "k": int(k),
    }


# --- scoring one embedding ---------------------------------------------------


def score_embedding(
    x: Any,
    labels: Any,
    batches: Any | None,
    *,
    lisi_neighbors: int,
    graph_neighbors: int,
    transfer_k: int,
    random_state: int,
) -> dict[str, Any]:
    """Compute every metric for one embedding, abstaining with a reason where needed.

    Returns ``{"metrics": {name: float | None}, "reasons": {name: str},
    "effective": {...}, "details": {...}}``. A metric is ``None`` exactly when
    its reason is present. ``lisi_neighbors`` and ``graph_neighbors`` count the
    cell itself (as scib-metrics does) and are capped at ``n_cells``; the caps
    actually used are in ``effective``.
    """
    metrics: dict[str, float | None] = {name: None for name in METRIC_NAMES}
    reasons: dict[str, str] = {}
    details: dict[str, Any] = {}
    arr = np.asarray(x, dtype=np.float64)
    n = arr.shape[0] if arr.ndim == 2 else 0
    effective = {
        "lisi_neighbors": int(min(lisi_neighbors, max(n, 1))),
        "graph_neighbors": int(min(graph_neighbors, max(n, 1))),
        "transfer_k": int(transfer_k),
        "n_cells": int(n),
    }

    degenerate = degeneracy_reason(arr)
    if degenerate is not None:
        for name in METRIC_NAMES:
            reasons[name] = f"not computed: embedding has {degenerate}"
        return {
            "metrics": metrics,
            "reasons": reasons,
            "effective": effective,
            "details": details,
        }

    details["duplicate_row_fraction"] = duplicate_row_fraction(arr)
    label_arr = np.asarray(labels).astype(str)
    n_labels = len(np.unique(label_arr))
    has_batches = batches is not None
    batch_arr = np.asarray(batches).astype(str) if has_batches else None
    n_batches = len(np.unique(batch_arr)) if has_batches else 0

    k_l, k_g = effective["lisi_neighbors"], effective["graph_neighbors"]
    dists, idx = exact_knn(arr, max(k_l, k_g))

    label_block = REASON_FEW_LABELS if n_labels < 2 else None
    batch_block = (
        REASON_NO_BATCH
        if not has_batches
        else (REASON_FEW_BATCHES if n_batches < 2 else None)
    )

    def attempt(name: str, fn, precondition: str | None = None) -> None:
        if precondition is not None:
            reasons[name] = precondition
            return
        try:
            value = fn()
        except ValueError as exc:
            reasons[name] = f"not computed: {exc}"
            return
        if value is None:
            reasons[name] = REASON_SIL_BATCH_UNDEFINED
            return
        metrics[name] = float(value)

    attempt("silhouette_label", lambda: silhouette_label(arr, label_arr), label_block)
    attempt(
        "isolated_labels",
        lambda: isolated_labels(arr, label_arr, batch_arr),
        label_block or batch_block,
    )

    if label_block is None:
        try:
            nmi, ari, pred = kmeans_nmi_ari(arr, label_arr, random_state=random_state)
            metrics["nmi_kmeans"], metrics["ari_kmeans"] = nmi, ari
            details["kmeans_n_clusters"] = len(np.unique(pred))
        except ValueError as exc:
            reasons["nmi_kmeans"] = reasons["ari_kmeans"] = f"not computed: {exc}"
    else:
        reasons["nmi_kmeans"] = reasons["ari_kmeans"] = label_block

    attempt(
        "clisi", lambda: clisi(dists[:, :k_l], idx[:, :k_l], label_arr), label_block
    )
    attempt(
        "ilisi", lambda: ilisi(dists[:, :k_l], idx[:, :k_l], batch_arr), batch_block
    )
    if label_block is None or batch_block is None:
        # cells whose kernel bandwidth search degenerates get LISI -1 upstream; count them
        probe = label_arr if label_block is None else batch_arr
        details["lisi_degenerate_cells"] = int(
            np.sum(lisi_per_cell(dists[:, :k_l], idx[:, :k_l], probe) < 0)
        )
    attempt(
        "graph_connectivity",
        lambda: graph_connectivity(dists[:, :k_g], idx[:, :k_g], label_arr),
        label_block,
    )
    attempt("bras", lambda: bras(arr, label_arr, batch_arr), label_block or batch_block)
    attempt(
        "silhouette_batch",
        lambda: silhouette_batch(arr, label_arr, batch_arr),
        label_block or batch_block,
    )

    if label_block is None and batch_block is None:
        try:
            transfer = knn_transfer_accuracy(arr, label_arr, batch_arr, k=transfer_k)
            metrics["knn_transfer_accuracy"] = transfer["accuracy"]
            details["knn_transfer"] = {
                "per_batch_accuracy": transfer["per_batch_accuracy"],
                "n_cells_with_unseen_label": transfer["n_cells_with_unseen_label"],
            }
        except ValueError as exc:
            reasons["knn_transfer_accuracy"] = f"not computed: {exc}"
    else:
        reasons["knn_transfer_accuracy"] = label_block or batch_block

    return {
        "metrics": metrics,
        "reasons": reasons,
        "effective": effective,
        "details": details,
    }


# --- verdict rule ------------------------------------------------------------


def verdict(
    diffs: Any,
    full_embedding: float | None = None,
    full_baseline: float | None = None,
) -> dict[str, Any]:
    """Apply the half-sampling rule to embedding-minus-baseline differences.

    ``diffs`` are the differences on the resamples; values with
    ``|d| <= DIFF_TOLERANCE`` count as zero. The verdict is ``not evaluated``
    when any difference is missing; ``tied`` when every difference is zero or
    both full-data values sit at or above ``CEILING``; ``higher`` when every
    difference is > 0 and the median exceeds ``SD_FACTOR`` standard deviations
    of the differences; ``lower`` symmetrically; ``not separable`` otherwise.
    Reported alongside: median and SD of the differences and the fraction that
    is positive. The verdict describes this cell sample and these fixed
    embeddings, nothing more.
    """
    values = list(diffs)
    n = len(values)
    missing = sum(1 for v in values if v is None or not np.isfinite(v))
    if n == 0 or missing:
        return {
            "verdict": "not evaluated",
            "median_diff": None,
            "sd_diff": None,
            "frac_positive": None,
            "n_resamples": n,
            "reason": f"{missing} of {n} resamples had no value"
            if n
            else "no resamples",
        }
    arr = np.asarray(values, dtype=np.float64)
    arr = np.where(np.abs(arr) <= DIFF_TOLERANCE, 0.0, arr)
    median = float(np.median(arr))
    sd = float(np.std(arr, ddof=1)) if n > 1 else 0.0
    at_ceiling = (
        full_embedding is not None
        and full_baseline is not None
        and full_embedding >= CEILING
        and full_baseline >= CEILING
    )
    reason = ""
    if np.all(arr == 0) or at_ceiling:
        label = "tied"
        reason = "both at ceiling" if at_ceiling else "no difference beyond tolerance"
    elif np.all(arr > 0) and median > SD_FACTOR * sd:
        label = "higher"
    elif np.all(arr < 0) and -median > SD_FACTOR * sd:
        label = "lower"
    else:
        label = "not separable"
        if np.all(arr > 0) or np.all(arr < 0):
            reason = f"consistent sign but |median| <= {SD_FACTOR:g} x SD"
        else:
            reason = "differences change sign across half-samples"
    return {
        "verdict": label,
        "median_diff": median,
        "sd_diff": sd,
        "frac_positive": float(np.mean(arr > 0)),
        "n_resamples": n,
        "reason": reason,
    }


# --- subsampling -------------------------------------------------------------


def stratified_subsample(
    labels: Any,
    batches: Any | None,
    *,
    fraction: float | None = None,
    n_cells: int | None = None,
    random_state: int = 0,
) -> np.ndarray:
    """Seeded stratified subsample of cell indices (strata = label x batch).

    Exactly one of ``fraction`` or ``n_cells`` sets the total size; the total is
    split across strata proportionally with largest-remainder rounding and at
    least one cell per non-empty stratum. Returns sorted indices.
    """
    if (fraction is None) == (n_cells is None):
        raise ValueError("give exactly one of fraction or n_cells")
    labels = np.asarray(labels).astype(str)
    n = labels.shape[0]
    if n == 0:
        raise ValueError("no cells to subsample")
    strata = (
        labels
        if batches is None
        else np.char.add(np.char.add(labels, "\x1f"), np.asarray(batches).astype(str))
    )
    uniq, inverse = np.unique(strata, return_inverse=True)
    sizes = np.bincount(inverse, minlength=len(uniq))
    total = round(fraction * n) if fraction is not None else int(n_cells)
    total = max(len(uniq), min(total, n))
    quotas = sizes * (total / n)
    take = np.floor(quotas).astype(int)
    take = np.maximum(take, 1)
    take = np.minimum(take, sizes)
    remainder = total - int(take.sum())
    order = np.argsort(-(quotas - np.floor(quotas)), kind="stable")
    i = 0
    while remainder > 0 and i < 10 * len(uniq):
        s = order[i % len(uniq)]
        if take[s] < sizes[s]:
            take[s] += 1
            remainder -= 1
        i += 1
    order_desc = np.argsort(-take, kind="stable")
    i = 0
    while remainder < 0 and i < 10 * len(uniq):
        s = order_desc[i % len(uniq)]
        if take[s] > 1:
            take[s] -= 1
            remainder += 1
        i += 1
    rng = np.random.default_rng(random_state)
    chosen: list[np.ndarray] = []
    for s in range(len(uniq)):
        members = np.flatnonzero(inverse == s)
        chosen.append(rng.choice(members, size=int(take[s]), replace=False))
    return np.sort(np.concatenate(chosen))
